import { db } from './db';
import { pregnancyWeeks } from '../shared/schema';

const weekData = [
  // ── FIRST TRIMESTER ──────────────────────────────────────────────
  {
    weekNumber: 1,
    trimester: 1,
    theme: 'Beginning & Becoming',
    babySizeComparison: 'Poppy seed',
    babySizeEmoji: '🌱',
    babyWeightGrams: '0.001',
    babyLengthCm: '0.1',
    babyDevelopment: '• Fertilisation has occurred and a single cell is dividing rapidly\n• The blastocyst is travelling toward your uterus to implant\n• Cells are already differentiating into what will become the baby and placenta',
    momBodyChanges: '• Your uterus is preparing its lining for implantation\n• Hormone levels are beginning to shift even before a positive test',
    commonSymptoms: 'Mild cramping, slight spotting (implantation bleeding)',
    suggestedFocus: 'mindset',
    affirmation: 'Something extraordinary is already happening inside you — even before you can feel it.',
  },
  {
    weekNumber: 2,
    trimester: 1,
    theme: 'Beginning & Becoming',
    babySizeComparison: 'Sesame seed',
    babySizeEmoji: '🫘',
    babyWeightGrams: '0.001',
    babyLengthCm: '0.2',
    babyDevelopment: '• Implantation is complete and the embryo is burrowed into the uterine lining\n• HCG production begins, triggering a positive pregnancy test\n• Cells are forming two layers: the epiblast (future baby) and hypoblast (future placenta)',
    momBodyChanges: '• HCG surges signal your body to pause the menstrual cycle\n• Progesterone rises to maintain the pregnancy lining',
    commonSymptoms: 'Breast tenderness, fatigue, heightened sense of smell',
    suggestedFocus: 'mindset',
    affirmation: 'You don\'t have to feel ready to be exactly where you\'re supposed to be.',
  },
  {
    weekNumber: 3,
    trimester: 1,
    theme: 'Beginning & Becoming',
    babySizeComparison: 'Pea',
    babySizeEmoji: '🟢',
    babyWeightGrams: '0.01',
    babyLengthCm: '0.4',
    babyDevelopment: '• The neural tube — the foundation of the brain and spinal cord — is beginning to form\n• The heart starts as a simple tube that will soon begin beating\n• Three distinct cell layers are developing that will form every organ and tissue',
    momBodyChanges: '• Morning sickness may begin as HCG peaks\n• Your blood volume starts increasing to support the growing embryo',
    commonSymptoms: 'Nausea, fatigue, mood fluctuations',
    suggestedFocus: 'physical',
    affirmation: 'Your body is doing something it has never done before. Give yourself grace for every hard moment.',
  },
  {
    weekNumber: 4,
    trimester: 1,
    theme: 'Beginning & Becoming',
    babySizeComparison: 'Blueberry',
    babySizeEmoji: '🫐',
    babyWeightGrams: '0.04',
    babyLengthCm: '0.6',
    babyDevelopment: '• The heart is beating for the first time — around 100–160 bpm\n• Arm and leg buds are emerging\n• The face is beginning to take shape with dark spots where the eyes will be',
    momBodyChanges: '• Your uterus is growing and you may feel occasional pulling or cramping\n• Increased blood flow can cause veins to become more visible',
    commonSymptoms: 'Nausea, food aversions, heightened emotions',
    suggestedFocus: 'mindset',
    affirmation: 'That little heartbeat? It matched yours the moment it started. You are already connected.',
  },
  {
    weekNumber: 5,
    trimester: 1,
    theme: 'Beginning & Becoming',
    babySizeComparison: 'Blueberry',
    babySizeEmoji: '🫐',
    babyWeightGrams: '0.07',
    babyLengthCm: '0.8',
    babyDevelopment: '• Brain development is happening rapidly — neurons are forming at an astonishing rate\n• Fingers and toes are beginning to form, though still webbed\n• The digestive system, lungs, and liver are taking shape',
    momBodyChanges: '• Your waistline may feel thicker even if nothing shows yet\n• Round ligament stretching can cause occasional sharp twinges',
    commonSymptoms: 'Bloating, frequent urination, emotional sensitivity',
    suggestedFocus: 'mindset',
    affirmation: 'It\'s okay to feel two things at once — excited and terrified are allowed to coexist.',
  },
  {
    weekNumber: 6,
    trimester: 1,
    theme: 'Beginning & Becoming',
    babySizeComparison: 'Raspberry',
    babySizeEmoji: '🍇',
    babyWeightGrams: '0.13',
    babyLengthCm: '1.2',
    babyDevelopment: '• The nose, lips, and eyelids are forming\n• The baby is making its first spontaneous movements, though too small to feel\n• Arm and leg bones are beginning to harden',
    momBodyChanges: '• Breast changes are significant — soreness, darkening areolas, visible veins\n• Your cervix has formed a protective mucus plug',
    commonSymptoms: 'Extreme fatigue, breast tenderness, nausea',
    suggestedFocus: 'physical',
    affirmation: 'Rest is not laziness right now. It is the most productive thing you can do.',
  },
  {
    weekNumber: 7,
    trimester: 1,
    theme: 'Beginning & Becoming',
    babySizeComparison: 'Kidney bean',
    babySizeEmoji: '🫘',
    babyWeightGrams: '0.8',
    babyLengthCm: '1.6',
    babyDevelopment: '• The brain is developing complex folds and growing faster than any other organ\n• Cartilage is forming and will soon harden into bone\n• Taste buds are beginning to appear on the tongue',
    momBodyChanges: '• Morning sickness may peak this week — it can happen at any time of day\n• You may be producing extra saliva (ptyalism)',
    commonSymptoms: 'Vomiting, strong food aversions, light-headedness',
    suggestedFocus: 'physical',
    affirmation: 'You are nourishing life even on the days you can barely keep anything down. That is strength.',
  },
  {
    weekNumber: 8,
    trimester: 1,
    theme: 'Beginning & Becoming',
    babySizeComparison: 'Grape',
    babySizeEmoji: '🍇',
    babyWeightGrams: '1.0',
    babyLengthCm: '2.0',
    babyDevelopment: '• All major organs are present in rudimentary form\n• The baby can move its arms and legs\n• Facial features are becoming more defined — tiny ears and eyelids are forming',
    momBodyChanges: '• Your uterus has doubled in size since conception\n• Skin changes may appear — some women notice a pregnancy glow, others notice breakouts',
    commonSymptoms: 'Constipation, indigestion, emotional waves',
    suggestedFocus: 'mindset',
    affirmation: 'You don\'t have to look pregnant to feel the magnitude of what is happening. It\'s real.',
  },
  {
    weekNumber: 9,
    trimester: 1,
    theme: 'Beginning & Becoming',
    babySizeComparison: 'Grape',
    babySizeEmoji: '🍇',
    babyWeightGrams: '2.0',
    babyLengthCm: '2.3',
    babyDevelopment: '• The embryo officially becomes a foetus this week\n• Tiny fingers and toes are fully separated\n• Reproductive organs are beginning to differentiate',
    momBodyChanges: '• Your clothes may feel tighter around the waist\n• Increased blood flow may cause nasal congestion',
    commonSymptoms: 'Fatigue, headaches, nasal stuffiness',
    suggestedFocus: 'mindset',
    affirmation: 'You are becoming someone new. That transformation is supposed to feel big.',
  },
  {
    weekNumber: 10,
    trimester: 1,
    theme: 'Beginning & Becoming',
    babySizeComparison: 'Kumquat',
    babySizeEmoji: '🍊',
    babyWeightGrams: '4.0',
    babyLengthCm: '3.1',
    babyDevelopment: '• All vital organs are formed and beginning to function together\n• Fingernails and toenails are growing\n• The baby can swallow and produce digestive juices',
    momBodyChanges: '• Your uterus is now the size of a large orange\n• Round ligament pain is common as things stretch',
    commonSymptoms: 'Round ligament pain, fatigue, emotional sensitivity',
    suggestedFocus: 'physical',
    affirmation: 'Your body is doing miraculous, invisible work. Honor it with kindness.',
  },
  {
    weekNumber: 11,
    trimester: 1,
    theme: 'Beginning & Becoming',
    babySizeComparison: 'Fig',
    babySizeEmoji: '🫐',
    babyWeightGrams: '7.0',
    babyLengthCm: '4.1',
    babyDevelopment: '• The baby is now making active movements — kicking and flipping\n• Hair follicles are forming all over the body\n• The diaphragm is developing — hiccups may begin soon',
    momBodyChanges: '• Nausea often begins to ease toward the end of this week\n• Your heart is pumping about 20% more blood than before pregnancy',
    commonSymptoms: 'Fatigue, heartburn, occasional dizziness',
    suggestedFocus: 'mindset',
    affirmation: 'The hardest stretch is nearly behind you. You made it through the beginning.',
  },
  {
    weekNumber: 12,
    trimester: 1,
    theme: 'Beginning & Becoming',
    babySizeComparison: 'Lime',
    babySizeEmoji: '🍋',
    babyWeightGrams: '14.0',
    babyLengthCm: '5.4',
    babyDevelopment: '• The baby\'s reflexes are developing — fingers open and close, toes curl\n• Brain synapses are forming at an incredible rate\n• The kidneys are producing urine and the baby can urinate into the amniotic fluid',
    momBodyChanges: '• The risk of miscarriage drops significantly after this week\n• Your uterus is moving up out of the pelvis and can be felt just above the pubic bone',
    commonSymptoms: 'Increased energy returning, reduced nausea, visible bump emerging',
    suggestedFocus: 'relationships',
    affirmation: 'You made it through the first chapter. Sharing this news is yours to decide, on your timeline.',
  },

  // ── SECOND TRIMESTER ─────────────────────────────────────────────
  {
    weekNumber: 13,
    trimester: 2,
    theme: 'Growing & Connecting',
    babySizeComparison: 'Lemon',
    babySizeEmoji: '🍋',
    babyWeightGrams: '23.0',
    babyLengthCm: '7.4',
    babyDevelopment: '• Vocal cords are forming\n• The placenta is now fully functioning and taking over hormone production\n• Bone marrow is beginning to produce blood cells',
    momBodyChanges: '• Energy often returns noticeably this week\n• Your bump may finally become visible to others',
    commonSymptoms: 'Increased appetite, round ligament stretching, occasional headaches',
    suggestedFocus: 'mindset',
    affirmation: 'Welcome to the part where you get to breathe again. You\'ve earned it.',
  },
  {
    weekNumber: 14,
    trimester: 2,
    theme: 'Growing & Connecting',
    babySizeComparison: 'Lemon',
    babySizeEmoji: '🍋',
    babyWeightGrams: '43.0',
    babyLengthCm: '8.7',
    babyDevelopment: '• The baby can squint, frown, and make facial expressions\n• Lanugo — fine, soft hair — is beginning to cover the body for warmth\n• The thyroid gland is producing hormones',
    momBodyChanges: '• Your skin may be glowing — increased blood flow and hormones affect complexion\n• Ligaments are loosening throughout your body in preparation for birth',
    commonSymptoms: 'Stuffy nose, bleeding gums, skin changes',
    suggestedFocus: 'physical',
    affirmation: 'Your body is softening to make room for everything that\'s coming. That softness is power.',
  },
  {
    weekNumber: 15,
    trimester: 2,
    theme: 'Growing & Connecting',
    babySizeComparison: 'Apple',
    babySizeEmoji: '🍎',
    babyWeightGrams: '70.0',
    babyLengthCm: '10.1',
    babyDevelopment: '• The baby can sense light through closed eyelids\n• Taste buds are fully developed and responding to your food choices\n• Legs are now longer than the arms',
    momBodyChanges: '• Your uterus is midway between your pubic bone and navel\n• Skin changes like the linea nigra may appear',
    commonSymptoms: 'Heartburn, back discomfort, vivid dreams',
    suggestedFocus: 'physical',
    affirmation: 'You are the first world your baby has ever known. You are already enough.',
  },
  {
    weekNumber: 16,
    trimester: 2,
    theme: 'Growing & Connecting',
    babySizeComparison: 'Avocado',
    babySizeEmoji: '🥑',
    babyWeightGrams: '100.0',
    babyLengthCm: '11.6',
    babyDevelopment: '• The baby\'s eyes are moving beneath closed lids\n• Scalp hair pattern is being established\n• Toenails are fully formed',
    momBodyChanges: '• You may feel the first flutters of movement — like butterflies or bubbles\n• Blood pressure may be lower than usual, causing occasional dizziness',
    commonSymptoms: 'Fluttering sensations, lower back ache, leg cramps',
    suggestedFocus: 'relationships',
    affirmation: 'The first time you feel them move, let yourself be completely in that moment.',
  },
  {
    weekNumber: 17,
    trimester: 2,
    theme: 'Growing & Connecting',
    babySizeComparison: 'Avocado',
    babySizeEmoji: '🥑',
    babyWeightGrams: '140.0',
    babyLengthCm: '13.0',
    babyDevelopment: '• Fat is beginning to accumulate under the baby\'s skin for insulation and energy\n• The umbilical cord is thickening and strengthening\n• The baby can hear — your voice is the most familiar sound in their world',
    momBodyChanges: '• Your centre of gravity is shifting as the bump grows\n• Increased blood flow can cause nosebleeds',
    commonSymptoms: 'Nosebleeds, dizziness when standing, stretch marks beginning',
    suggestedFocus: 'relationships',
    affirmation: 'They already know your voice. You are already home to them.',
  },
  {
    weekNumber: 18,
    trimester: 2,
    theme: 'Growing & Connecting',
    babySizeComparison: 'Sweet potato',
    babySizeEmoji: '🍠',
    babyWeightGrams: '190.0',
    babyLengthCm: '14.2',
    babyDevelopment: '• The baby yawns, stretches, and makes facial expressions\n• Myelin is beginning to coat the nerves for faster signal transmission\n• A unique set of fingerprints is fully formed',
    momBodyChanges: '• Your belly button may begin to pop out\n• Braxton Hicks contractions can begin — practice waves your body is preparing',
    commonSymptoms: 'Braxton Hicks, swollen feet, increased appetite',
    suggestedFocus: 'mindset',
    affirmation: 'Your body is already practicing. Every wave is preparation, not threat.',
  },
  {
    weekNumber: 19,
    trimester: 2,
    theme: 'Growing & Connecting',
    babySizeComparison: 'Sweet potato',
    babySizeEmoji: '🍠',
    babyWeightGrams: '240.0',
    babyLengthCm: '15.3',
    babyDevelopment: '• Vernix caseosa — a waxy protective coating — covers the baby\'s skin\n• The sensory areas of the brain are developing — touch, taste, smell, hearing\n• The baby is establishing sleep-wake cycles, often opposite to yours',
    momBodyChanges: '• You may feel kicks and jabs more consistently now\n• Your uterus has reached your navel',
    commonSymptoms: 'Back pain, hip discomfort, Braxton Hicks',
    suggestedFocus: 'physical',
    affirmation: 'Every kick is a conversation. Your baby is already reaching out to you.',
  },
  {
    weekNumber: 20,
    trimester: 2,
    theme: 'Growing & Connecting',
    babySizeComparison: 'Banana',
    babySizeEmoji: '🍌',
    babyWeightGrams: '300.0',
    babyLengthCm: '25.6',
    babyDevelopment: '• This is the halfway point — the baby is fully formed, just growing\n• Swallowing amniotic fluid helps develop the digestive system\n• The baby can hear music, conversation, and your heartbeat',
    momBodyChanges: '• You are at the halfway point — a moment worth marking\n• The uterus now reaches the navel',
    commonSymptoms: 'Shortness of breath, heartburn, swelling in feet',
    suggestedFocus: 'relationships',
    affirmation: 'Halfway. Look how far you have already come. Look at what you have already done.',
  },
  {
    weekNumber: 21,
    trimester: 2,
    theme: 'Growing & Connecting',
    babySizeComparison: 'Banana',
    babySizeEmoji: '🍌',
    babyWeightGrams: '360.0',
    babyLengthCm: '26.7',
    babyDevelopment: '• The baby\'s eyebrows and eyelids are fully formed\n• Bone marrow is taking over blood cell production from the liver\n• The baby can taste what you eat through the amniotic fluid',
    momBodyChanges: '• Your posture changes as the bump shifts your centre of gravity\n• Stretch marks may appear on the abdomen, hips, or thighs',
    commonSymptoms: 'Leg cramps, varicose veins, stretch marks',
    suggestedFocus: 'physical',
    affirmation: 'Those marks are not damage. They are a record of everything your body expanded to hold.',
  },
  {
    weekNumber: 22,
    trimester: 2,
    theme: 'Growing & Connecting',
    babySizeComparison: 'Carrot',
    babySizeEmoji: '🥕',
    babyWeightGrams: '430.0',
    babyLengthCm: '27.8',
    babyDevelopment: '• Eyelids open and the baby can perceive light and dark\n• The inner ear is developed enough for the baby to sense movement\n• Grip strength is developing as the baby grabs the umbilical cord',
    momBodyChanges: '• Your body is producing relaxin, softening ligaments throughout\n• You may notice more pronounced Braxton Hicks as your body rehearses',
    commonSymptoms: 'Pelvic pressure, heartburn, trouble sleeping',
    suggestedFocus: 'relationships',
    affirmation: 'Bonding doesn\'t always feel magical. Talking, touching, simply being present — it all counts.',
  },
  {
    weekNumber: 23,
    trimester: 2,
    theme: 'Growing & Connecting',
    babySizeComparison: 'Carrot',
    babySizeEmoji: '🥕',
    babyWeightGrams: '501.0',
    babyLengthCm: '28.9',
    babyDevelopment: '• The baby\'s sense of movement is fully functional — they can feel you sway\n• Blood vessels in the lungs are developing in preparation for breathing\n• The brain is growing rapidly and becoming more complex',
    momBodyChanges: '• Your uterus is about 3.5 cm above your navel\n• Oedema (swelling) in ankles and feet may increase',
    commonSymptoms: 'Swelling, insomnia, shortness of breath',
    suggestedFocus: 'mindset',
    affirmation: 'When you dance, sway, or simply walk — your baby feels every step with you.',
  },
  {
    weekNumber: 24,
    trimester: 2,
    theme: 'Growing & Connecting',
    babySizeComparison: 'Grapefruit',
    babySizeEmoji: '🍊',
    babyWeightGrams: '600.0',
    babyLengthCm: '30.0',
    babyDevelopment: '• The inner ear is fully developed — the baby has a sense of balance\n• Taste buds are responding to flavours in the amniotic fluid\n• The brain is forming billions of neurons this week',
    momBodyChanges: '• Your fundus (top of the uterus) is now at navel height\n• Glucose screening tests are typically done this week',
    commonSymptoms: 'Backache, pelvic girdle pain, Braxton Hicks',
    suggestedFocus: 'physical',
    affirmation: 'You are in the thick of it now. Steady does it — you are doing so well.',
  },
  {
    weekNumber: 25,
    trimester: 2,
    theme: 'Growing & Connecting',
    babySizeComparison: 'Grapefruit',
    babySizeEmoji: '🍊',
    babyWeightGrams: '660.0',
    babyLengthCm: '34.6',
    babyDevelopment: '• The baby\'s nostrils are beginning to open — practice breathing movements begin\n• Capillaries are forming under the skin, making it appear pink\n• The baby responds to loud sounds by startling',
    momBodyChanges: '• Your uterus is about the size of a soccer ball\n• Haemorrhoids may develop due to increased pressure',
    commonSymptoms: 'Haemorrhoids, heartburn, restless leg syndrome',
    suggestedFocus: 'relationships',
    affirmation: 'Asking for help is not weakness. Let the people who love you show up for you.',
  },
  {
    weekNumber: 26,
    trimester: 2,
    theme: 'Growing & Connecting',
    babySizeComparison: 'Head of lettuce',
    babySizeEmoji: '🥬',
    babyWeightGrams: '760.0',
    babyLengthCm: '35.6',
    babyDevelopment: '• Eyes are beginning to open — the baby can detect light and shadow\n• The brain is taking control of rhythmic breathing movements\n• The immune system is developing, receiving antibodies from you through the placenta',
    momBodyChanges: '• You may feel short of breath as the uterus presses on the diaphragm\n• Sleep becomes increasingly difficult to find a comfortable position',
    commonSymptoms: 'Shortness of breath, insomnia, Braxton Hicks',
    suggestedFocus: 'mindset',
    affirmation: 'Discomfort in pregnancy does not mean something is wrong. Your body is making space.',
  },
  {
    weekNumber: 27,
    trimester: 2,
    theme: 'Growing & Connecting',
    babySizeComparison: 'Head of lettuce',
    babySizeEmoji: '🥬',
    babyWeightGrams: '875.0',
    babyLengthCm: '36.6',
    babyDevelopment: '• The brain is very active — rapid eye movement (REM) sleep begins\n• The baby is practicing swallowing and sucking reflexes\n• Lung development accelerates in preparation for life outside the womb',
    momBodyChanges: '• The third trimester begins next week — take stock of how far you\'ve come\n• Your centre of gravity has shifted significantly',
    commonSymptoms: 'Pelvic pressure, fatigue returning, frequent urination',
    suggestedFocus: 'relationships',
    affirmation: 'You have grown a whole person to this point. That deserves to be felt, not just noted.',
  },

  // ── THIRD TRIMESTER ──────────────────────────────────────────────
  {
    weekNumber: 28,
    trimester: 3,
    theme: 'Preparing & Trusting',
    babySizeComparison: 'Eggplant',
    babySizeEmoji: '🍆',
    babyWeightGrams: '1005.0',
    babyLengthCm: '37.6',
    babyDevelopment: '• The baby can blink with eyelashes now fully formed\n• Brain tissue is developing rapidly with increasing surface folds\n• The baby is accumulating body fat for warmth and energy reserves after birth',
    momBodyChanges: '• Colostrum (first milk) may begin leaking from your breasts\n• You may feel the baby\'s hiccups as regular rhythmic movements',
    commonSymptoms: 'Leaking breasts, back pain, trouble sleeping',
    suggestedFocus: 'mindset',
    affirmation: 'The third trimester is about trust. Trust your body. Trust your instincts. You were made for this.',
  },
  {
    weekNumber: 29,
    trimester: 3,
    theme: 'Preparing & Trusting',
    babySizeComparison: 'Eggplant',
    babySizeEmoji: '🍆',
    babyWeightGrams: '1153.0',
    babyLengthCm: '38.6',
    babyDevelopment: '• The baby\'s bones are fully developed though still soft and flexible\n• The brain is directing rhythmic breathing movements — practice for birth\n• Muscle tone is increasing with each week',
    momBodyChanges: '• Symphysis pubis dysfunction (SPD) can cause pelvic pain\n• Varicose veins may worsen as blood volume peaks',
    commonSymptoms: 'Pelvic pain, shortness of breath, frequent Braxton Hicks',
    suggestedFocus: 'physical',
    affirmation: 'Every uncomfortable day is one day closer. Your body is preparing beautifully.',
  },
  {
    weekNumber: 30,
    trimester: 3,
    theme: 'Preparing & Trusting',
    babySizeComparison: 'Butternut squash',
    babySizeEmoji: '🎃',
    babyWeightGrams: '1319.0',
    babyLengthCm: '39.9',
    babyDevelopment: '• The baby\'s eyes can focus on objects close by\n• The brain is forming millions of connections every day\n• Bone marrow has fully taken over red blood cell production',
    momBodyChanges: '• Heartburn may intensify as the uterus presses on the stomach\n• You may feel more waddling in your walk — this is normal',
    commonSymptoms: 'Severe heartburn, swelling, fatigue',
    suggestedFocus: 'mindset',
    affirmation: 'You don\'t have to hold it all together. Some days are just about getting through — and that is enough.',
  },
  {
    weekNumber: 31,
    trimester: 3,
    theme: 'Preparing & Trusting',
    babySizeComparison: 'Butternut squash',
    babySizeEmoji: '🎃',
    babyWeightGrams: '1502.0',
    babyLengthCm: '41.1',
    babyDevelopment: '• All five senses are functioning\n• The baby moves into a head-down position in preparation for birth\n• Rapid brain and nervous system development continues',
    momBodyChanges: '• Frequent urination returns as the baby drops lower\n• You may experience vivid or anxious dreams about birth',
    commonSymptoms: 'Frequent urination, vivid dreams, pelvic pressure',
    suggestedFocus: 'mindset',
    affirmation: 'Fear of birth is not a sign you\'re not ready. It\'s a sign you understand the magnitude of what\'s ahead.',
  },
  {
    weekNumber: 32,
    trimester: 3,
    theme: 'Preparing & Trusting',
    babySizeComparison: 'Coconut',
    babySizeEmoji: '🥥',
    babyWeightGrams: '1702.0',
    babyLengthCm: '42.4',
    babyDevelopment: '• Toenails, fingernails, and hair are all present and growing\n• The baby practices breathing by inhaling amniotic fluid\n• Immune antibodies are transferring from you to baby at an accelerated rate',
    momBodyChanges: '• Braxton Hicks contractions become more frequent and noticeable\n• Difficulty finding a comfortable sleeping position is nearly universal now',
    commonSymptoms: 'Braxton Hicks, insomnia, shortness of breath',
    suggestedFocus: 'physical',
    affirmation: 'You are building a human. The exhaustion is real, and it means something.',
  },
  {
    weekNumber: 33,
    trimester: 3,
    theme: 'Preparing & Trusting',
    babySizeComparison: 'Coconut',
    babySizeEmoji: '🥥',
    babyWeightGrams: '1918.0',
    babyLengthCm: '43.7',
    babyDevelopment: '• The skull is not yet fused — it remains flexible for birth\n• The baby\'s immune system is receiving its final boosts\n• Sleep cycles are well-established with REM patterns similar to a newborn',
    momBodyChanges: '• You may have gained 10–12kg by this point\n• Carpal tunnel syndrome (wrist numbness/tingling) is common',
    commonSymptoms: 'Wrist pain, back ache, difficulty walking long distances',
    suggestedFocus: 'relationships',
    affirmation: 'Have the conversations you need to have with the people who will support you through birth. Ask for what you need.',
  },
  {
    weekNumber: 34,
    trimester: 3,
    theme: 'Preparing & Trusting',
    babySizeComparison: 'Pineapple',
    babySizeEmoji: '🍍',
    babyWeightGrams: '2146.0',
    babyLengthCm: '45.0',
    babyDevelopment: '• The central nervous system and lungs are maturing rapidly\n• The baby\'s fat deposits are smoothing out the skin\n• Vernix coating is thickening to protect the skin until birth',
    momBodyChanges: '• Your cervix may begin to soften and efface in preparation for labour\n• Sleep deprivation is near universal — nap without guilt',
    commonSymptoms: 'Pelvic pressure, Braxton Hicks, general discomfort',
    suggestedFocus: 'mindset',
    affirmation: 'You are allowed to be done and ready and a little bit afraid all at the same time.',
  },
  {
    weekNumber: 35,
    trimester: 3,
    theme: 'Preparing & Trusting',
    babySizeComparison: 'Pineapple',
    babySizeEmoji: '🍍',
    babyWeightGrams: '2383.0',
    babyLengthCm: '46.2',
    babyDevelopment: '• Kidney development is complete\n• The hearing system is fully functional — the baby responds to your voice with calming behaviour\n• Most lanugo has shed and the baby has grown rounder with fat deposits',
    momBodyChanges: '• You may feel the baby "drop" lower into the pelvis (lightening)\n• Breathing may become easier but pelvic pressure increases',
    commonSymptoms: 'Lightening, increased pelvic pressure, difficulty walking',
    suggestedFocus: 'physical',
    affirmation: 'Your body is already in the process of letting go. Labour begins long before you feel it.',
  },
  {
    weekNumber: 36,
    trimester: 3,
    theme: 'Preparing & Trusting',
    babySizeComparison: 'Honeydew',
    babySizeEmoji: '🍈',
    babyWeightGrams: '2622.0',
    babyLengthCm: '47.4',
    babyDevelopment: '• The baby gains about 28 grams per day from this point\n• Gums are hardening in preparation for nursing\n• The digestive system is mature and ready for breast milk',
    momBodyChanges: '• Your cervix may begin to dilate\n• Increased discharge and possible loss of mucus plug is normal',
    commonSymptoms: 'Cervical pressure, mucus discharge, nesting urge',
    suggestedFocus: 'relationships',
    affirmation: 'Nesting is instinct. Create the space that feels safe for what\'s coming.',
  },
  {
    weekNumber: 37,
    trimester: 3,
    theme: 'Preparing & Trusting',
    babySizeComparison: 'Honeydew',
    babySizeEmoji: '🍈',
    babyWeightGrams: '2859.0',
    babyLengthCm: '48.6',
    babyDevelopment: '• The baby is considered early term — lungs are nearly fully mature\n• The baby is practicing breathing, sucking, and swallowing in coordination\n• Brain and lung development still continues until week 39',
    momBodyChanges: '• Cervical changes continue — dilation, effacement, softening\n• You may feel strong surges of nesting energy',
    commonSymptoms: 'Intense nesting urge, Braxton Hicks, cervical pressure',
    suggestedFocus: 'mindset',
    affirmation: 'This waiting is not empty time. It is the last chapter of the life you have known. Be here for it.',
  },
  {
    weekNumber: 38,
    trimester: 3,
    theme: 'Preparing & Trusting',
    babySizeComparison: 'Watermelon',
    babySizeEmoji: '🍉',
    babyWeightGrams: '3083.0',
    babyLengthCm: '49.8',
    babyDevelopment: '• The baby has a firm grasp reflex ready for the moment of birth\n• Vernix is mostly absorbed — the skin is smooth and plump\n• The brain continues its extraordinary development (and will for years after birth)',
    momBodyChanges: '• Real contractions may begin any time — irregular at first, then patterned\n• Your body may feel the heaviest it ever has',
    commonSymptoms: 'Lightning crotch, emotional intensity, early labour signs',
    suggestedFocus: 'mindset',
    affirmation: 'You are ready. Not because you have all the answers, but because your baby chose you.',
  },
  {
    weekNumber: 39,
    trimester: 3,
    theme: 'Preparing & Trusting',
    babySizeComparison: 'Watermelon',
    babySizeEmoji: '🍉',
    babyWeightGrams: '3288.0',
    babyLengthCm: '50.7',
    babyDevelopment: '• The baby is full term\n• Antibodies continue transferring to boost the newborn immune system\n• The baby\'s skull remains flexible, designed to navigate the birth canal',
    momBodyChanges: '• Labour can begin at any moment — contractions, water breaking, or a show of blood\n• Emotionally you may cycle between calm, excited, and overwhelmed rapidly',
    commonSymptoms: 'Intense pressure, irregular contractions, emotional waves',
    suggestedFocus: 'mindset',
    affirmation: 'When it starts, remember: every wave brings you closer to meeting them. Surrender to the current.',
  },
  {
    weekNumber: 40,
    trimester: 3,
    theme: 'Preparing & Trusting',
    babySizeComparison: 'Watermelon',
    babySizeEmoji: '🍉',
    babyWeightGrams: '3462.0',
    babyLengthCm: '51.2',
    babyDevelopment: '• The baby is fully developed and ready for life outside the womb\n• Fat stores are complete — the baby will use these in the first days of life\n• The placenta is beginning to age — nature\'s way of signalling it\'s time',
    momBodyChanges: '• Your body and your baby are in conversation — labour begins when they both agree it\'s time\n• Trust your instincts above all else in these final days',
    commonSymptoms: 'Strong contractions, water breaking, intense pressure',
    suggestedFocus: 'mindset',
    affirmation: 'This is the moment everything has been building toward. You are not alone. You were never alone.',
  },
];

async function seedPregnancyWeeks() {
  console.log('Seeding pregnancy_weeks table...');

  const existing = await db.select().from(pregnancyWeeks).limit(1);
  if (existing.length > 0) {
    console.log('pregnancy_weeks already seeded. Clearing and re-seeding...');
    await db.delete(pregnancyWeeks);
  }

  await db.insert(pregnancyWeeks).values(weekData);
  console.log(`✓ Seeded ${weekData.length} weeks of pregnancy data.`);
}

seedPregnancyWeeks()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error('Seed failed:', err);
    process.exit(1);
  });
