import { db } from "./db";
import { intakeQuestions } from "@shared/schema";

const intakeData = [
  {
    questionId: "1.1",
    phase: 1,
    orderNumber: 1,
    questionText: "What's your name?",
    questionType: "text_input",
    category: "core_profile",
    required: true,
    answerOptions: null,
    scoringMap: {},
  },
  {
    questionId: "1.2",
    phase: 1,
    orderNumber: 2,
    questionText: "When is your baby due?",
    questionType: "date_picker",
    category: "core_profile",
    required: true,
    answerOptions: null,
    scoringMap: {},
  },
  {
    questionId: "1.3",
    phase: 1,
    orderNumber: 3,
    questionText: "What's your relationship status?",
    questionType: "single_select",
    category: "core_profile",
    required: true,
    answerOptions: [
      { value: "A", label: "Single (parenting alone)" },
      { value: "B", label: "In a relationship" },
      { value: "C", label: "Married/Partnered" },
      { value: "D", label: "It's complicated" },
    ],
    scoringMap: {
      A: { flags: { single_mother: true } },
      B: {},
      C: {},
      D: { flags: { relationship_complicated: true } },
    },
  },
  {
    questionId: "1.4",
    phase: 1,
    orderNumber: 4,
    questionText: "Who do you live with right now?",
    questionType: "multi_select",
    category: "core_profile",
    required: true,
    answerOptions: [
      { value: "A", label: "I live alone" },
      { value: "B", label: "With my partner/spouse" },
      { value: "C", label: "With my parents/family" },
      { value: "D", label: "With roommates/friends" },
      { value: "E", label: "Other" },
    ],
    scoringMap: {
      A: { flags: { lives_alone: true }, season_points: { tender: 1 } },
      B: {},
      C: {},
      D: {},
      E: {},
    },
  },
  {
    questionId: "2.1",
    phase: 2,
    orderNumber: 5,
    questionText: "How are you feeling about pregnancy right now?",
    questionType: "single_select",
    category: "mindset",
    required: true,
    answerOptions: [
      { value: "A", label: "Overwhelmed and anxious most days" },
      { value: "B", label: "A mix of excited and nervous" },
      { value: "C", label: "Mostly calm and positive" },
      { value: "D", label: "Exhausted but hanging in there" },
      { value: "E", label: "Uncertain — it changes day to day" },
    ],
    scoringMap: {
      A: { season_points: { tender: 2 } },
      B: { season_points: { grounding: 1 } },
      C: { season_points: { expanding: 2 } },
      D: { season_points: { restorative: 2 } },
      E: { season_points: { grounding: 1 } },
    },
  },
  {
    questionId: "2.2",
    phase: 2,
    orderNumber: 6,
    questionText: "When you think about giving birth, what comes to mind first?",
    questionType: "single_select",
    category: "mindset",
    required: true,
    answerOptions: [
      { value: "A", label: "Fear and worry about complications" },
      { value: "B", label: "Excitement — I can't wait to meet my baby" },
      { value: "C", label: "I try not to think about it too much" },
      { value: "D", label: "I feel prepared and informed" },
      { value: "E", label: "A mix of everything honestly" },
    ],
    scoringMap: {
      A: { season_points: { tender: 2 } },
      B: { season_points: { expanding: 1 } },
      C: { season_points: { grounding: 1 }, flags: { birth_avoidant: true } },
      D: { season_points: { expanding: 2 } },
      E: { season_points: { grounding: 1 } },
    },
  },
  {
    questionId: "2.3",
    phase: 2,
    orderNumber: 7,
    questionText: "How do you usually cope when you feel stressed?",
    questionType: "single_select",
    category: "mindset",
    required: true,
    answerOptions: [
      { value: "A", label: "I talk it through with someone I trust" },
      { value: "B", label: "I need time alone to process" },
      { value: "C", label: "I distract myself until it passes" },
      { value: "D", label: "I make a plan and take action" },
      { value: "E", label: "I tend to bottle things up" },
    ],
    scoringMap: {
      A: { season_points: { grounding: 1 } },
      B: { season_points: { restorative: 1 } },
      C: { season_points: { grounding: 1 } },
      D: { season_points: { expanding: 1 } },
      E: { season_points: { tender: 2 }, flags: { emotional_suppression: true } },
    },
  },
  {
    questionId: "2.4",
    phase: 2,
    orderNumber: 8,
    questionText: "What's your biggest worry about becoming a mother?",
    questionType: "single_select",
    category: "mindset",
    required: true,
    answerOptions: [
      { value: "A", label: "Losing my identity or sense of self" },
      { value: "B", label: "Not being a good enough mother" },
      { value: "C", label: "The impact on my relationship" },
      { value: "D", label: "Managing everything practically (finances, work, time)" },
      { value: "E", label: "My own mental health and wellbeing" },
    ],
    scoringMap: {
      A: { season_points: { grounding: 2 }, flags: { identity_concern: true } },
      B: { season_points: { tender: 2 } },
      C: { season_points: { grounding: 1 }, flags: { relationship_concern: true } },
      D: { season_points: { expanding: 1 } },
      E: { season_points: { restorative: 2 }, flags: { mental_health_concern: true } },
    },
  },
  {
    questionId: "2.5",
    phase: 2,
    orderNumber: 9,
    questionText: "How connected do you feel to your baby right now?",
    questionType: "single_select",
    category: "mindset",
    required: true,
    answerOptions: [
      { value: "A", label: "Deeply connected — I talk and sing to them" },
      { value: "B", label: "It's growing, especially with kicks and movement" },
      { value: "C", label: "It still feels abstract and hard to believe" },
      { value: "D", label: "I feel guilty that I don't feel more connected" },
      { value: "E", label: "I'm taking it day by day" },
    ],
    scoringMap: {
      A: { season_points: { expanding: 2 } },
      B: { season_points: { expanding: 1, grounding: 1 } },
      C: { season_points: { grounding: 1 } },
      D: { season_points: { tender: 2 }, flags: { bonding_guilt: true } },
      E: { season_points: { grounding: 1 } },
    },
  },
  {
    questionId: "2.6",
    phase: 2,
    orderNumber: 10,
    questionText: "How would you describe your sleep lately?",
    questionType: "single_select",
    category: "mindset",
    required: true,
    answerOptions: [
      { value: "A", label: "I'm sleeping well most nights" },
      { value: "B", label: "Restless — I wake up a lot" },
      { value: "C", label: "Racing thoughts keep me awake" },
      { value: "D", label: "I'm exhausted but can't seem to rest properly" },
      { value: "E", label: "It varies night to night" },
    ],
    scoringMap: {
      A: { season_points: { expanding: 1 } },
      B: { season_points: { restorative: 1 } },
      C: { season_points: { tender: 1 }, flags: { sleep_anxiety: true } },
      D: { season_points: { restorative: 2 } },
      E: { season_points: { grounding: 1 } },
    },
  },
  {
    questionId: "2.7",
    phase: 2,
    orderNumber: 11,
    questionText: "How do you feel about asking for help?",
    questionType: "single_select",
    category: "mindset",
    required: true,
    answerOptions: [
      { value: "A", label: "I'm comfortable asking when I need it" },
      { value: "B", label: "I'd rather figure things out on my own" },
      { value: "C", label: "I want to ask but feel like a burden" },
      { value: "D", label: "I don't really have anyone to ask" },
      { value: "E", label: "It depends on what I need help with" },
    ],
    scoringMap: {
      A: { season_points: { expanding: 1 } },
      B: { season_points: { grounding: 1 }, flags: { hyper_independent: true } },
      C: { season_points: { tender: 2 } },
      D: { season_points: { tender: 2 }, flags: { low_support: true } },
      E: { season_points: { grounding: 1 } },
    },
  },
  {
    questionId: "2.8",
    phase: 2,
    orderNumber: 12,
    questionText: "What kind of mother do you hope to be?",
    questionType: "single_select",
    category: "mindset",
    required: true,
    answerOptions: [
      { value: "A", label: "Patient, calm, and emotionally available" },
      { value: "B", label: "Fun, adventurous, and spontaneous" },
      { value: "C", label: "Organised, structured, and providing stability" },
      { value: "D", label: "Different from how I was raised" },
      { value: "E", label: "I'm still figuring that out" },
    ],
    scoringMap: {
      A: { season_points: { restorative: 1, grounding: 1 } },
      B: { season_points: { expanding: 2 } },
      C: { season_points: { grounding: 2 } },
      D: { season_points: { tender: 1 }, flags: { intergenerational_healing: true } },
      E: { season_points: { grounding: 1 } },
    },
  },
  {
    questionId: "2.9",
    phase: 2,
    orderNumber: 13,
    questionText: "How has your mood been overall in the past two weeks?",
    questionType: "single_select",
    category: "mindset",
    required: true,
    answerOptions: [
      { value: "A", label: "Mostly positive and stable" },
      { value: "B", label: "Up and down — emotional rollercoaster" },
      { value: "C", label: "Consistently low or flat" },
      { value: "D", label: "Irritable and easily frustrated" },
      { value: "E", label: "Numb or disconnected" },
    ],
    scoringMap: {
      A: { season_points: { expanding: 1 } },
      B: { season_points: { grounding: 1 } },
      C: { season_points: { tender: 2 }, flags: { low_mood: true } },
      D: { season_points: { restorative: 1 } },
      E: { season_points: { tender: 2 }, flags: { emotional_numbness: true } },
    },
  },
  {
    questionId: "2.10",
    phase: 2,
    orderNumber: 14,
    questionText: "What best describes your self-care right now?",
    questionType: "single_select",
    category: "mindset",
    required: true,
    answerOptions: [
      { value: "A", label: "I prioritise it and have a routine" },
      { value: "B", label: "I try but it often falls to the bottom of the list" },
      { value: "C", label: "What self-care? I'm in survival mode" },
      { value: "D", label: "I feel guilty when I take time for myself" },
      { value: "E", label: "I'm not sure what self-care looks like for me" },
    ],
    scoringMap: {
      A: { season_points: { expanding: 2 } },
      B: { season_points: { grounding: 1 } },
      C: { season_points: { restorative: 2 }, flags: { burnout_risk: true } },
      D: { season_points: { tender: 1 }, flags: { self_care_guilt: true } },
      E: { season_points: { grounding: 1 } },
    },
  },
  {
    questionId: "3.1",
    phase: 3,
    orderNumber: 15,
    questionText: "How supported do you feel by your partner (or co-parent)?",
    questionType: "single_select",
    category: "relationships",
    required: true,
    answerOptions: [
      { value: "A", label: "Very supported — we're a team" },
      { value: "B", label: "Somewhat — but we could communicate better" },
      { value: "C", label: "Not very — I feel mostly alone in this" },
      { value: "D", label: "It's complicated right now" },
      { value: "E", label: "I'm doing this without a partner" },
    ],
    scoringMap: {
      A: { season_points: { expanding: 1 } },
      B: { season_points: { grounding: 1 } },
      C: { season_points: { tender: 2 }, flags: { partner_disconnect: true } },
      D: { season_points: { tender: 1 }, flags: { relationship_strain: true } },
      E: { season_points: { tender: 1 }, flags: { solo_parenting: true } },
    },
  },
  {
    questionId: "3.2",
    phase: 3,
    orderNumber: 16,
    questionText: "Have you and your partner discussed how responsibilities will change after baby?",
    questionType: "single_select",
    category: "relationships",
    required: true,
    answerOptions: [
      { value: "A", label: "Yes, we have a clear plan" },
      { value: "B", label: "We've talked about it loosely" },
      { value: "C", label: "Not really — we keep putting it off" },
      { value: "D", label: "I'm afraid to bring it up" },
      { value: "E", label: "Not applicable — I'm parenting solo" },
    ],
    scoringMap: {
      A: { season_points: { expanding: 2 } },
      B: { season_points: { grounding: 1 } },
      C: { season_points: { grounding: 1 } },
      D: { season_points: { tender: 2 }, flags: { conflict_avoidant: true } },
      E: { flags: { solo_parenting: true } },
    },
  },
  {
    questionId: "3.3",
    phase: 3,
    orderNumber: 17,
    questionText: "How would you describe your relationship with your own mother?",
    questionType: "single_select",
    category: "relationships",
    required: true,
    answerOptions: [
      { value: "A", label: "Close and supportive" },
      { value: "B", label: "Loving but complicated" },
      { value: "C", label: "Distant or strained" },
      { value: "D", label: "She's no longer living" },
      { value: "E", label: "I'd rather not go into it" },
    ],
    scoringMap: {
      A: { season_points: { expanding: 1 } },
      B: { season_points: { grounding: 1 } },
      C: { season_points: { tender: 1 }, flags: { maternal_wound: true } },
      D: { season_points: { tender: 1 }, flags: { mother_loss: true } },
      E: { season_points: { tender: 1 }, flags: { maternal_wound: true } },
    },
  },
  {
    questionId: "3.4",
    phase: 3,
    orderNumber: 18,
    questionText: "Do you have friends who are also mothers or expecting?",
    questionType: "single_select",
    category: "relationships",
    required: true,
    answerOptions: [
      { value: "A", label: "Yes, a close group I can lean on" },
      { value: "B", label: "A few, but we're not super close" },
      { value: "C", label: "Not really — I'm the first in my circle" },
      { value: "D", label: "I've drifted from friends since getting pregnant" },
      { value: "E", label: "I'm looking for that kind of community" },
    ],
    scoringMap: {
      A: { season_points: { expanding: 1 } },
      B: { season_points: { grounding: 1 } },
      C: { season_points: { grounding: 1 }, flags: { peer_isolation: true } },
      D: { season_points: { tender: 1 }, flags: { social_withdrawal: true } },
      E: { season_points: { grounding: 1 } },
    },
  },
  {
    questionId: "3.5",
    phase: 3,
    orderNumber: 19,
    questionText: "How do you feel about your body right now?",
    questionType: "single_select",
    category: "physical",
    required: true,
    answerOptions: [
      { value: "A", label: "Amazed at what it's doing" },
      { value: "B", label: "Uncomfortable but accepting" },
      { value: "C", label: "Disconnected from my body" },
      { value: "D", label: "Struggling with body image" },
      { value: "E", label: "It changes day to day" },
    ],
    scoringMap: {
      A: { season_points: { expanding: 2 } },
      B: { season_points: { grounding: 1 } },
      C: { season_points: { restorative: 1 } },
      D: { season_points: { tender: 2 }, flags: { body_image_concern: true } },
      E: { season_points: { grounding: 1 } },
    },
  },
  {
    questionId: "3.6",
    phase: 3,
    orderNumber: 20,
    questionText: "How are you feeling about work and career right now?",
    questionType: "single_select",
    category: "practical",
    required: true,
    answerOptions: [
      { value: "A", label: "I have a clear plan for leave and return" },
      { value: "B", label: "Anxious about managing career and motherhood" },
      { value: "C", label: "Relieved to take a break from work" },
      { value: "D", label: "Worried about finances" },
      { value: "E", label: "Uncertain about what I want" },
    ],
    scoringMap: {
      A: { season_points: { expanding: 1 } },
      B: { season_points: { grounding: 2 }, flags: { career_anxiety: true } },
      C: { season_points: { restorative: 1 } },
      D: { season_points: { tender: 1 }, flags: { financial_stress: true } },
      E: { season_points: { grounding: 1 } },
    },
  },
  {
    questionId: "3.7",
    phase: 3,
    orderNumber: 21,
    questionText: "Have you experienced anxiety or depression before pregnancy?",
    questionType: "single_select",
    category: "mental_health",
    required: true,
    answerOptions: [
      { value: "A", label: "No, this is all new to me" },
      { value: "B", label: "Yes, mild and managed" },
      { value: "C", label: "Yes, and I'm currently managing it" },
      { value: "D", label: "Yes, and pregnancy has made it harder" },
      { value: "E", label: "I'd prefer not to answer" },
    ],
    scoringMap: {
      A: { season_points: { expanding: 1 } },
      B: { season_points: { grounding: 1 }, flags: { mental_health_history: true } },
      C: { season_points: { restorative: 1 }, flags: { active_mental_health: true } },
      D: { season_points: { tender: 2 }, flags: { mental_health_worsening: true } },
      E: {},
    },
  },
  {
    questionId: "3.8",
    phase: 3,
    orderNumber: 22,
    questionText: "What are you most looking forward to about motherhood?",
    questionType: "single_select",
    category: "readiness",
    required: true,
    answerOptions: [
      { value: "A", label: "The unconditional love and bond" },
      { value: "B", label: "Watching my child grow and learn" },
      { value: "C", label: "Building a family and home together" },
      { value: "D", label: "Becoming a stronger version of myself" },
      { value: "E", label: "I'm honestly not sure yet — and that's okay" },
    ],
    scoringMap: {
      A: { season_points: { expanding: 1 } },
      B: { season_points: { expanding: 1 } },
      C: { season_points: { grounding: 1 } },
      D: { season_points: { grounding: 1, expanding: 1 } },
      E: { season_points: { tender: 1, grounding: 1 } },
    },
  },
  {
    questionId: "3.9",
    phase: 3,
    orderNumber: 23,
    questionText: "How much time do you spend on your phone or social media daily?",
    questionType: "single_select",
    category: "lifestyle",
    required: true,
    answerOptions: [
      { value: "A", label: "Less than 1 hour" },
      { value: "B", label: "1-2 hours" },
      { value: "C", label: "3-4 hours" },
      { value: "D", label: "More than 4 hours" },
      { value: "E", label: "I'm trying to cut back" },
    ],
    scoringMap: {
      A: { season_points: { expanding: 1 } },
      B: {},
      C: { season_points: { restorative: 1 } },
      D: { season_points: { restorative: 1 }, flags: { screen_time_concern: true } },
      E: { season_points: { grounding: 1 } },
    },
  },
  {
    questionId: "3.10",
    phase: 3,
    orderNumber: 24,
    questionText: "If PrePartum could help you with one thing, what would it be?",
    questionType: "single_select",
    category: "personalization",
    required: true,
    answerOptions: [
      { value: "A", label: "Help me feel less anxious and more confident" },
      { value: "B", label: "Help me prepare practically for what's coming" },
      { value: "C", label: "Help me connect with my baby and my emotions" },
      { value: "D", label: "Help me strengthen my relationships" },
      { value: "E", label: "Help me take better care of myself" },
    ],
    scoringMap: {
      A: { season_points: { tender: 1, grounding: 1 } },
      B: { season_points: { grounding: 2 } },
      C: { season_points: { expanding: 2 } },
      D: { season_points: { grounding: 1 } },
      E: { season_points: { restorative: 2 } },
    },
  },
];

export async function seedIntakeQuestions() {
  const existing = await db.select().from(intakeQuestions);
  if (existing.length > 0) {
    console.log(`Intake questions already seeded (${existing.length} found), skipping.`);
    return;
  }

  await db.insert(intakeQuestions).values(intakeData as any);
  console.log(`Seeded ${intakeData.length} intake questions across 3 phases.`);
}
