import { db } from './db';
import { pregnancyWeeks } from '../shared/schema';

const weekData = [
  {
    weekNumber: 1, trimester: 1, theme: 'Beginning & Becoming',
    babySizeComparison: 'poppy seed', babySizeEmoji: '🌱',
    babyWeightGrams: '0.1', babyLengthCm: '0.1',
    babyDevelopment: 'Fertilization occurs. A single cell begins dividing rapidly. The blastocyst travels toward the uterus.',
    momBodyChanges: 'Most women do not know they are pregnant yet. Hormones begin shifting quietly.',
    commonSymptoms: 'None yet, possibly fatigue',
    suggestedFocus: 'mindset',
    affirmation: 'Something sacred just began inside you — even before you knew it.',
  },
  {
    weekNumber: 2, trimester: 1, theme: 'Beginning & Becoming',
    babySizeComparison: 'sesame seed', babySizeEmoji: '🌱',
    babyWeightGrams: '0.1', babyLengthCm: '0.1',
    babyDevelopment: 'Implantation happens. The embryo burrows into the uterine lining. The placenta begins forming.',
    momBodyChanges: 'Light spotting may occur. Hormone surge begins.',
    commonSymptoms: 'Light spotting, mild cramping',
    suggestedFocus: 'mindset',
    affirmation: 'Your body is already doing something extraordinary without being asked.',
  },
  {
    weekNumber: 3, trimester: 1, theme: 'Beginning & Becoming',
    babySizeComparison: 'pea', babySizeEmoji: '🟢',
    babyWeightGrams: '0.1', babyLengthCm: '0.2',
    babyDevelopment: 'The neural tube — which becomes the brain and spine — begins forming. Heart cells start developing.',
    momBodyChanges: 'hCG hormone rises rapidly. Pregnancy test may turn positive.',
    commonSymptoms: 'Tender breasts, light fatigue',
    suggestedFocus: 'mindset',
    affirmation: 'You do not need to have it all figured out. Just show up.',
  },
  {
    weekNumber: 4, trimester: 1, theme: 'Beginning & Becoming',
    babySizeComparison: 'blueberry', babySizeEmoji: '🫐',
    babyWeightGrams: '0.1', babyLengthCm: '0.4',
    babyDevelopment: 'Brain, heart, and spinal cord are forming. The heart begins beating.',
    momBodyChanges: 'Missed period. Pregnancy test clearly positive. Nausea may begin.',
    commonSymptoms: 'Nausea, fatigue, sore breasts, frequent urination',
    suggestedFocus: 'mindset',
    affirmation: 'A missed period just changed your whole life. Take a breath. You have got this.',
  },
  {
    weekNumber: 5, trimester: 1, theme: 'Beginning & Becoming',
    babySizeComparison: 'blueberry', babySizeEmoji: '🫐',
    babyWeightGrams: '0.1', babyLengthCm: '0.6',
    babyDevelopment: 'Facial features begin forming. Arm and leg buds appear. Heart now beats 100+ times per minute.',
    momBodyChanges: 'Nausea often peaks this week. Sense of smell intensifies.',
    commonSymptoms: 'Morning sickness, food aversions, exhaustion',
    suggestedFocus: 'physical',
    affirmation: 'Even when your body feels foreign to you, it is working perfectly.',
  },
  {
    weekNumber: 6, trimester: 1, theme: 'Beginning & Becoming',
    babySizeComparison: 'raspberry', babySizeEmoji: '🍇',
    babyWeightGrams: '0.1', babyLengthCm: '0.8',
    babyDevelopment: 'Eyes and ears are forming. Fingers and toes beginning to develop. Brain growing rapidly.',
    momBodyChanges: 'Uterus begins expanding. Bloating common. Emotional swings are normal.',
    commonSymptoms: 'Bloating, mood swings, nausea, breast tenderness',
    suggestedFocus: 'mindset',
    affirmation: 'Your emotions are not a problem to be managed. They are information.',
  },
  {
    weekNumber: 7, trimester: 1, theme: 'Beginning & Becoming',
    babySizeComparison: 'kidney bean', babySizeEmoji: '🫘',
    babyWeightGrams: '1', babyLengthCm: '1.3',
    babyDevelopment: 'Hands and feet have webbed fingers and toes. Brain develops at 100 new neurons per minute.',
    momBodyChanges: 'Frequent urination increases. Saliva increases.',
    commonSymptoms: 'Excess saliva, frequent urination, fatigue',
    suggestedFocus: 'relationships',
    affirmation: 'Who do you want in your corner for this? Now is the time to ask.',
  },
  {
    weekNumber: 8, trimester: 1, theme: 'Beginning & Becoming',
    babySizeComparison: 'grape', babySizeEmoji: '🍇',
    babyWeightGrams: '2', babyLengthCm: '1.6',
    babyDevelopment: 'Fingers and toes are distinct. Eyelids forming. Taste buds developing. Baby can now move.',
    momBodyChanges: 'Waistline beginning to thicken. First prenatal appointment usually this week.',
    commonSymptoms: 'Heartburn, constipation, fatigue',
    suggestedFocus: 'mindset',
    affirmation: 'You are allowed to feel excited and terrified at the same time.',
  },
  {
    weekNumber: 9, trimester: 1, theme: 'Beginning & Becoming',
    babySizeComparison: 'grape', babySizeEmoji: '🍇',
    babyWeightGrams: '3', babyLengthCm: '2.3',
    babyDevelopment: 'Embryo is now officially a fetus. Muscles forming. Tiny nose, eyelids, earlobes taking shape.',
    momBodyChanges: 'Uterus is now the size of a grapefruit. Round ligament pain may begin.',
    commonSymptoms: 'Visible veins on breasts, ligament pain, mood swings',
    suggestedFocus: 'relationships',
    affirmation: 'Your relationship to yourself is changing too. Be gentle with her.',
  },
  {
    weekNumber: 10, trimester: 1, theme: 'Beginning & Becoming',
    babySizeComparison: 'kumquat', babySizeEmoji: '🍊',
    babyWeightGrams: '4', babyLengthCm: '3.1',
    babyDevelopment: 'All vital organs formed and starting to work. Fingernails and hair follicles forming. Baby can swallow.',
    momBodyChanges: 'Nausea may start to ease. Visible bump for some.',
    commonSymptoms: 'Continued nausea, fatigue, emotional sensitivity',
    suggestedFocus: 'mindset',
    affirmation: 'The hardest part is often the invisible part. You are doing the work no one can see.',
  },
  {
    weekNumber: 11, trimester: 1, theme: 'Beginning & Becoming',
    babySizeComparison: 'fig', babySizeEmoji: '🍈',
    babyWeightGrams: '7', babyLengthCm: '4.1',
    babyDevelopment: 'Fingers and toes no longer webbed. Baby moving actively — stretching, rolling, hiccupping.',
    momBodyChanges: 'Energy may start returning. Skin changes — some glow, some breakouts.',
    commonSymptoms: 'Skin changes, vivid dreams, nasal congestion',
    suggestedFocus: 'physical',
    affirmation: 'Your body is doing things it has never done before. That deserves wonder, not judgment.',
  },
  {
    weekNumber: 12, trimester: 1, theme: 'Beginning & Becoming',
    babySizeComparison: 'lime', babySizeEmoji: '🍋',
    babyWeightGrams: '14', babyLengthCm: '5.4',
    babyDevelopment: 'First trimester complete. Reflexes developing. Kidneys producing urine. Miscarriage risk drops significantly.',
    momBodyChanges: 'First trimester ends. Many women share their news this week.',
    commonSymptoms: 'Reducing nausea, lingering fatigue',
    suggestedFocus: 'relationships',
    affirmation: 'You made it through the first chapter. That was real courage.',
  },
  {
    weekNumber: 13, trimester: 2, theme: 'Growing & Connecting',
    babySizeComparison: 'lemon', babySizeEmoji: '🍋',
    babyWeightGrams: '23', babyLengthCm: '7.4',
    babyDevelopment: 'Baby can make facial expressions. Fingerprints forming. Vocal cords developing.',
    momBodyChanges: 'Energy typically returns. Baby bump becomes more visible.',
    commonSymptoms: 'Round ligament pain, increased appetite, less nausea',
    suggestedFocus: 'mindset',
    affirmation: 'The fog is lifting. Welcome to the second chapter.',
  },
  {
    weekNumber: 14, trimester: 2, theme: 'Growing & Connecting',
    babySizeComparison: 'lemon', babySizeEmoji: '🍋',
    babyWeightGrams: '43', babyLengthCm: '8.7',
    babyDevelopment: 'Baby can squint, frown, grimace. Lanugo covers body. Kidneys producing urine.',
    momBodyChanges: 'Hair and nails growing faster. Sex drive may increase.',
    commonSymptoms: 'Increased energy, glowing skin, round ligament pain',
    suggestedFocus: 'relationships',
    affirmation: 'Your partner is watching you become someone new. Let them in.',
  },
  {
    weekNumber: 15, trimester: 2, theme: 'Growing & Connecting',
    babySizeComparison: 'apple', babySizeEmoji: '🍎',
    babyWeightGrams: '70', babyLengthCm: '10.1',
    babyDevelopment: 'Baby moving vigorously. Bones hardening. Baby can sense light through the uterine wall.',
    momBodyChanges: 'Belly button may start to protrude. Linea nigra may appear.',
    commonSymptoms: 'Nose bleeds, bleeding gums, back pain',
    suggestedFocus: 'physical',
    affirmation: 'Your body is not the same body it was. That is not a loss — it is an expansion.',
  },
  {
    weekNumber: 16, trimester: 2, theme: 'Growing & Connecting',
    babySizeComparison: 'avocado', babySizeEmoji: '🥑',
    babyWeightGrams: '100', babyLengthCm: '11.6',
    babyDevelopment: 'Eyes can move. Ears in final position. Baby practices breathing. Circulatory system fully functioning.',
    momBodyChanges: 'First flutters of movement (quickening) may be felt.',
    commonSymptoms: 'Back ache, swollen feet, heartburn',
    suggestedFocus: 'mindset',
    affirmation: 'Those first flutters are real. Something is telling you it is here.',
  },
  {
    weekNumber: 17, trimester: 2, theme: 'Growing & Connecting',
    babySizeComparison: 'avocado', babySizeEmoji: '🥑',
    babyWeightGrams: '140', babyLengthCm: '13',
    babyDevelopment: 'Baby developing fat stores. Sweat glands forming. Umbilical cord growing stronger.',
    momBodyChanges: 'Belly growing visibly. Pregnancy brain is real.',
    commonSymptoms: 'Forgetfulness, dizziness, back pain',
    suggestedFocus: 'relationships',
    affirmation: 'It is okay to ask for help carrying things — physically and emotionally.',
  },
  {
    weekNumber: 18, trimester: 2, theme: 'Growing & Connecting',
    babySizeComparison: 'sweet potato', babySizeEmoji: '🍠',
    babyWeightGrams: '190', babyLengthCm: '14.2',
    babyDevelopment: 'Baby can yawn, hiccup, roll. Myelin forming. Can hear sounds from outside the womb.',
    momBodyChanges: 'Anatomy scan typically happens around week 18–20. Movements now felt clearly.',
    commonSymptoms: 'Leg cramps, swollen ankles, early Braxton Hicks',
    suggestedFocus: 'mindset',
    affirmation: 'Your baby can hear you now. What do you want them to know?',
  },
  {
    weekNumber: 19, trimester: 2, theme: 'Growing & Connecting',
    babySizeComparison: 'sweet potato', babySizeEmoji: '🍠',
    babyWeightGrams: '240', babyLengthCm: '15.3',
    babyDevelopment: 'Vernix covers baby skin. Senses developing rapidly — taste, smell, hearing.',
    momBodyChanges: 'Baby kicks may now be felt from outside by others.',
    commonSymptoms: 'Hip pain, heartburn, vivid dreams',
    suggestedFocus: 'relationships',
    affirmation: 'Share this kick with someone you love. You do not have to carry this joy alone.',
  },
  {
    weekNumber: 20, trimester: 2, theme: 'Growing & Connecting',
    babySizeComparison: 'banana', babySizeEmoji: '🍌',
    babyWeightGrams: '300', babyLengthCm: '16.4',
    babyDevelopment: 'Halfway point. Movements coordinated. Tooth buds forming. Nails reaching fingertips.',
    momBodyChanges: 'Anatomy scan typically complete. Belly button may pop out.',
    commonSymptoms: 'Shortness of breath, varicose veins, Braxton Hicks',
    suggestedFocus: 'mindset',
    affirmation: 'Halfway there. Pause and honor how far you have come.',
  },
  {
    weekNumber: 21, trimester: 2, theme: 'Growing & Connecting',
    babySizeComparison: 'banana', babySizeEmoji: '🍌',
    babyWeightGrams: '360', babyLengthCm: '26.7',
    babyDevelopment: 'Baby swallowing amniotic fluid and developing taste preferences. Bone marrow producing blood cells.',
    momBodyChanges: 'Stretch marks may appear. Skin may feel itchy.',
    commonSymptoms: 'Itchy skin, stretch marks, Braxton Hicks',
    suggestedFocus: 'physical',
    affirmation: 'These marks are not flaws. They are the story of what your body did for love.',
  },
  {
    weekNumber: 22, trimester: 2, theme: 'Growing & Connecting',
    babySizeComparison: 'papaya', babySizeEmoji: '🍈',
    babyWeightGrams: '430', babyLengthCm: '27.8',
    babyDevelopment: 'Baby has fingerprints. Lips distinct. Eyes formed but irises lack pigment. Grip reflex developing.',
    momBodyChanges: 'Feeling baby hiccups is common now. Linea nigra may darken.',
    commonSymptoms: 'Swelling, heartburn, back pain',
    suggestedFocus: 'relationships',
    affirmation: 'Your relationship patterns are showing up more clearly now. That is the work.',
  },
  {
    weekNumber: 23, trimester: 2, theme: 'Growing & Connecting',
    babySizeComparison: 'papaya', babySizeEmoji: '🍈',
    babyWeightGrams: '500', babyLengthCm: '28.9',
    babyDevelopment: 'Baby responds to familiar voices. Lungs developing. Rapid brain development.',
    momBodyChanges: 'Braxton Hicks may feel stronger. Feet may swell.',
    commonSymptoms: 'Swollen feet, leg cramps, insomnia',
    suggestedFocus: 'mindset',
    affirmation: 'Your voice is already something your baby knows. Use it — to yourself and to them.',
  },
  {
    weekNumber: 24, trimester: 2, theme: 'Growing & Connecting',
    babySizeComparison: 'grapefruit', babySizeEmoji: '🍊',
    babyWeightGrams: '600', babyLengthCm: '30',
    babyDevelopment: 'Baby reaches viability milestone. Face fully formed. Brain developing rapidly.',
    momBodyChanges: 'Glucose tolerance test typically this week. Heartburn intensifies.',
    commonSymptoms: 'Heartburn, carpal tunnel, frequent urination',
    suggestedFocus: 'mindset',
    affirmation: 'Viability week. Your baby is fighting to be here. So are you.',
  },
  {
    weekNumber: 25, trimester: 2, theme: 'Growing & Connecting',
    babySizeComparison: 'grapefruit', babySizeEmoji: '🍊',
    babyWeightGrams: '660', babyLengthCm: '34.6',
    babyDevelopment: 'Hair growing. Fat deposits building. Baby startled by loud noises. Hands open and close.',
    momBodyChanges: 'Round ligament pain may intensify. Hemorrhoids may appear.',
    commonSymptoms: 'Hemorrhoids, round ligament pain, restlessness',
    suggestedFocus: 'relationships',
    affirmation: 'Who needs to know what you need right now? Say it out loud this week.',
  },
  {
    weekNumber: 26, trimester: 2, theme: 'Growing & Connecting',
    babySizeComparison: 'head of lettuce', babySizeEmoji: '🥬',
    babyWeightGrams: '760', babyLengthCm: '35.6',
    babyDevelopment: 'Eyes can open and close. Baby responds to light. Immune system developing.',
    momBodyChanges: 'Belly may feel tight. Back pain increases. Third trimester approaching.',
    commonSymptoms: 'Back pain, insomnia, swelling',
    suggestedFocus: 'physical',
    affirmation: 'Rest is not laziness right now. It is the most productive thing you can do.',
  },
  {
    weekNumber: 27, trimester: 2, theme: 'Growing & Connecting',
    babySizeComparison: 'head of lettuce', babySizeEmoji: '🥬',
    babyWeightGrams: '875', babyLengthCm: '36.6',
    babyDevelopment: 'Second trimester ends. Brain tissue developing rapidly. Baby can recognize your voice.',
    momBodyChanges: 'You may feel clumsy. Center of gravity shifted. Shortness of breath increases.',
    commonSymptoms: 'Shortness of breath, Braxton Hicks, fatigue',
    suggestedFocus: 'mindset',
    affirmation: 'Two trimesters done. You have grown an entire human being from nothing. Let that land.',
  },
  {
    weekNumber: 28, trimester: 3, theme: 'Preparing & Trusting',
    babySizeComparison: 'zucchini', babySizeEmoji: '🥒',
    babyWeightGrams: '1005', babyLengthCm: '37.6',
    babyDevelopment: 'Third trimester begins. Baby can blink. REM sleep cycles begin — baby may be dreaming.',
    momBodyChanges: 'Shortness of breath intensifies. Back pain increases.',
    commonSymptoms: 'Shortness of breath, insomnia, Braxton Hicks',
    suggestedFocus: 'mindset',
    affirmation: 'The third trimester is where you get real with yourself. It is time.',
  },
  {
    weekNumber: 29, trimester: 3, theme: 'Preparing & Trusting',
    babySizeComparison: 'zucchini', babySizeEmoji: '🥒',
    babyWeightGrams: '1153', babyLengthCm: '38.6',
    babyDevelopment: 'Bones fully developed but still soft. Muscles and lungs maturing. Baby can distinguish light from dark.',
    momBodyChanges: 'Heartburn at peak. Swelling in feet and ankles worsens.',
    commonSymptoms: 'Heartburn, swollen ankles, frequent urination',
    suggestedFocus: 'relationships',
    affirmation: 'What conversations have you been putting off? This is the week to have them.',
  },
  {
    weekNumber: 30, trimester: 3, theme: 'Preparing & Trusting',
    babySizeComparison: 'butternut squash', babySizeEmoji: '🎃',
    babyWeightGrams: '1319', babyLengthCm: '39.9',
    babyDevelopment: 'Brain forming billions of neurons. Lanugo beginning to shed. Baby gaining half a pound per week.',
    momBodyChanges: 'May feel baby hiccups daily. Colostrum may begin leaking.',
    commonSymptoms: 'Colostrum leakage, pelvic pressure, leg cramps',
    suggestedFocus: 'physical',
    affirmation: 'Your body is preparing for something it has never done before. Trust that it knows how.',
  },
  {
    weekNumber: 31, trimester: 3, theme: 'Preparing & Trusting',
    babySizeComparison: 'butternut squash', babySizeEmoji: '🎃',
    babyWeightGrams: '1502', babyLengthCm: '41.1',
    babyDevelopment: 'Baby moving into head-down position. All five senses functioning. Rapid brain development.',
    momBodyChanges: 'Shortness of breath persists. Braxton Hicks more frequent.',
    commonSymptoms: 'Braxton Hicks, shortness of breath, insomnia',
    suggestedFocus: 'mindset',
    affirmation: 'Fear is not a stop sign. It is a sign you care deeply about what is coming.',
  },
  {
    weekNumber: 32, trimester: 3, theme: 'Preparing & Trusting',
    babySizeComparison: 'coconut', babySizeEmoji: '🥥',
    babyWeightGrams: '1702', babyLengthCm: '42.4',
    babyDevelopment: 'Skeleton hardening. Skin less transparent as fat builds. Immune system getting antibodies from mom.',
    momBodyChanges: 'Waddling gait begins. Nesting instinct may kick in strongly.',
    commonSymptoms: 'Nesting urge, pelvic pressure, fatigue',
    suggestedFocus: 'relationships',
    affirmation: 'Nesting is not just for the baby. You are also preparing a home for the new version of yourself.',
  },
  {
    weekNumber: 33, trimester: 3, theme: 'Preparing & Trusting',
    babySizeComparison: 'coconut', babySizeEmoji: '🥥',
    babyWeightGrams: '1918', babyLengthCm: '43.7',
    babyDevelopment: 'Immune system strengthening. Skull bones remain soft and flexible for birth. Rapid weight gain.',
    momBodyChanges: 'Sleep becomes difficult. Frequent bathroom trips through the night.',
    commonSymptoms: 'Insomnia, frequent urination at night, back pain',
    suggestedFocus: 'mindset',
    affirmation: 'Sleeplessness now is preparing you for what is coming. Your body is already adapting.',
  },
  {
    weekNumber: 34, trimester: 3, theme: 'Preparing & Trusting',
    babySizeComparison: 'pineapple', babySizeEmoji: '🍍',
    babyWeightGrams: '2146', babyLengthCm: '45',
    babyDevelopment: 'Central nervous system and lungs maturing rapidly. Baby practicing breathing movements.',
    momBodyChanges: 'Pelvis begins softening and separating. Walking may feel uncomfortable.',
    commonSymptoms: 'Pelvic girdle pain, lightning crotch, Braxton Hicks',
    suggestedFocus: 'physical',
    affirmation: 'Your body knows how to open. That has always been true of you.',
  },
  {
    weekNumber: 35, trimester: 3, theme: 'Preparing & Trusting',
    babySizeComparison: 'pineapple', babySizeEmoji: '🍍',
    babyWeightGrams: '2383', babyLengthCm: '46.2',
    babyDevelopment: 'Lungs nearly mature. Liver and kidneys functioning well. Gaining half a pound per week.',
    momBodyChanges: 'Baby may drop lower into the pelvis. Easier to breathe but more pelvic pressure.',
    commonSymptoms: 'Pelvic pressure, easier breathing, increased discharge',
    suggestedFocus: 'relationships',
    affirmation: 'Have you told the people who matter most what this journey has meant to you?',
  },
  {
    weekNumber: 36, trimester: 3, theme: 'Preparing & Trusting',
    babySizeComparison: 'honeydew melon', babySizeEmoji: '🍈',
    babyWeightGrams: '2622', babyLengthCm: '47.4',
    babyDevelopment: 'Baby shedding vernix and lanugo. Sucking and swallowing reflexes strong. Gaining one ounce per day.',
    momBodyChanges: 'Group B strep test typically this week. Cervix may begin to dilate.',
    commonSymptoms: 'Cervical pressure, nesting urge peak, Braxton Hicks',
    suggestedFocus: 'mindset',
    affirmation: 'You have done everything right. Now it is time to surrender to what comes next.',
  },
  {
    weekNumber: 37, trimester: 3, theme: 'Preparing & Trusting',
    babySizeComparison: 'honeydew melon', babySizeEmoji: '🍈',
    babyWeightGrams: '2859', babyLengthCm: '48.6',
    babyDevelopment: 'Baby is considered early term. All organs functioning. Head may be engaged in pelvis.',
    momBodyChanges: 'Mucus plug may release. Cervix continues thinning and dilating.',
    commonSymptoms: 'Mucus plug loss, pelvic heaviness, back labor sensations',
    suggestedFocus: 'relationships',
    affirmation: 'You have prepared as much as any human can. What comes next requires trust, not preparation.',
  },
  {
    weekNumber: 38, trimester: 3, theme: 'Preparing & Trusting',
    babySizeComparison: 'watermelon', babySizeEmoji: '🍉',
    babyWeightGrams: '3083', babyLengthCm: '49.8',
    babyDevelopment: 'Baby considered full term. Lungs fully mature. Brain and nervous system continue developing.',
    momBodyChanges: 'Cervix softening and effacing. False labor contractions may intensify.',
    commonSymptoms: 'Strong Braxton Hicks, nesting peak, pelvic pressure',
    suggestedFocus: 'mindset',
    affirmation: 'You are ready. Not because everything is perfect. Because you are.',
  },
  {
    weekNumber: 39, trimester: 3, theme: 'Preparing & Trusting',
    babySizeComparison: 'watermelon', babySizeEmoji: '🍉',
    babyWeightGrams: '3288', babyLengthCm: '50.7',
    babyDevelopment: 'Full term. Brain still developing rapidly. All systems ready for life outside the womb.',
    momBodyChanges: 'Cervix may be fully effaced. Real labor contractions may begin.',
    commonSymptoms: 'Real contractions beginning, water breaking, pelvic pressure',
    suggestedFocus: 'relationships',
    affirmation: 'Let the people who love you hold you right now. You have earned every hand offered to you.',
  },
  {
    weekNumber: 40, trimester: 3, theme: 'Preparing & Trusting',
    babySizeComparison: 'watermelon', babySizeEmoji: '🍉',
    babyWeightGrams: '3462', babyLengthCm: '51.2',
    babyDevelopment: 'Full term. All organs, systems, and reflexes fully developed. Waiting for the perfect moment.',
    momBodyChanges: 'Due date week. Body ready for labor.',
    commonSymptoms: 'Active labor, water breaking, contractions',
    suggestedFocus: 'mindset',
    affirmation: 'Everything you have carried, every fear you sat with — it was all preparing you for this moment. You are ready.',
  },
];

async function seedPregnancyWeeks() {
  console.log('Re-seeding pregnancy_weeks table with updated data...');
  await db.delete(pregnancyWeeks);
  await db.insert(pregnancyWeeks).values(weekData);
  console.log(`✓ Seeded ${weekData.length} weeks of pregnancy data.`);
}

seedPregnancyWeeks()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error('Seed failed:', err);
    process.exit(1);
  });
